#拍卖公棚url
gongpeng:
  api_url: "https://service.jingjia.guguxinge.com/api//client/auction/api/v1/auctions"
  delay: 3
  max_retries: 3
  timeout: 10
  params:
    pagesize: 999999
    pageno: 0
    finishstarttime: 0
    finishendtime: 0
    key: ""
#拍卖鸽分组url
auction_sections:
  api_url: "https://service.jingjia.guguxinge.com/api//client/auction/api/v1/auctions/{gongpeng_id}/sections"
  delay: 2
  max_retries: 3
  timeout: 10
  params:
    pagesize: 999999
    pageno: 0

#拍卖鸽列表url
auction_pigeons:
  api_url: "https://service.jingjia.guguxinge.com/api//client/auction/api/v1/auctions/{gongpeng_id}/pigeons"
  delay: 2
  max_retries: 3
  timeout: 10
  params:
    pagesize: 999999
    pageno: 0
    orderby: 'live'
    sectionid: 0


#当前拍卖鸽
current_pigeons:
  api_url: "https://service.jingjia.guguxinge.com/api//client/auction/api/v1/auctions/317/pigeons/current"
  delay: 2
  max_retries: 3
  timeout: 10

#拍卖鸽历史出价记录
pid_pigeons:
  api_url: "https://service.jingjia.guguxinge.com/api//client/transaction/api/v1/pigeons/{pid}/bids"
  delay: 2
  max_retries: 3
  timeout: 10
  params:
    pagesize: 999999
    pageno: 0

#直播间url
TARGET_URL: "https://cdn.guguxinge.com/jingjia/#/live?auctionid=317&h=%5B%22home%22%2C%22auctiondetl%22%5D"

context:
  xlsx_path: "D:\\pareedo\\gugu\\gugu2\\context\\拍卖手册.xlsx"